### ISSUE TITLE
Child Tax Credit calculation is wrong

### ISSUE THREAD

**Issue by trevan** [nick264/gop-tax-plan-calculator#1]
The child tax credit amount is wrong.  Instead of:

 outputs.ChildTaxCredit = reduce(ctc, inputs.GrossIncome, relevant_rules.ChildTaxCreditPhaseOut, 1000, 50 * inputs.DependentChildren, true)

It should be:

 outputs.ChildTaxCredit = reduce(ctc, inputs.GrossIncome, relevant_rules.ChildTaxCreditPhaseOut, 1000, 50, true)

It isn't reduced $50 * DependentChildren for each $1000 over the limit, it is just reduced by $50 for each $1000.

**Comment by nick264** [comment]
Awesome, thank you! We read somewhere that it was $50 per child, but looks like you're right that it's $50 total https://www.irs.gov/pub/irs-pdf/p972.pdf

Will fix this!
